### ISSUE TITLE
Demo, documentation site down

### ISSUE THREAD

**Issue by openhouse** [lifegadget/ui-image#1]
Going to http://development.ui-image.divshot.io/ shows the message "Site Unavailable"

It looks like the hosting provider divshot was acquired by google and all sites they were hosting have been shut down.

https://divshot.com

**Comment by yankeeinlondon** [comment]
Hmm. Thanks for pointing it out. I had thought I had already rehosted it on google. I'll have a look tomorrow morning.

**Comment by yankeeinlondon** [comment]
Checked on my iPad and it is hosted on Firebase here: https://ui-image.firebaseapp.com/ . I'll update the Readme tomorrow.

**Comment by openhouse** [comment]
Great! Thanks!
